/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_physics_box2d_ContactEdge */

#ifndef _Included_com_badlogic_gdx_physics_box2d_ContactEdge
#define _Included_com_badlogic_gdx_physics_box2d_ContactEdge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_physics_box2d_ContactEdge
 * Method:    jniGetNext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_box2d_ContactEdge_jniGetNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_ContactEdge
 * Method:    jniGetOther
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_box2d_ContactEdge_jniGetOther
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_badlogic_gdx_physics_box2d_ContactEdge
 * Method:    jniGetContact
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_physics_box2d_ContactEdge_jniGetContact
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
